### ISSUE TITLE
Facet operator with repeat/layer

### ISSUE THREAD

**Issue by john-guerra** [vega/vega-lite-api#112] opened 2020-04-28 15:08 UTC
There seems to be a bug with the vega-lite-api. There doesn't seem to be a way of using the facet operator with a repeat/layer chart in its spec.

I want to make this facet then repeat-layer chart but using vega-lite-api:

```javascript
{
  "data" : { "values": data } ,
  "facet" : { "field": "Ciudad", "type": "nominal" },  
  "spec" : {
    "repeat": {
      "layer": [ "Muertes No hacer nada", "Muertes Cuarentena" ]
    },
    "spec": {
      "mark": {
        "type": "line"
      },
      "encoding": {
        "x": { "field": "Fecha", "type": "temporal" },
        "y": { "field": { "repeat": "layer" }, "type": "quantitative" },
        "color": { "datum": { "repeat": "layer" }}
      }
    }
  }
}
```

So I'm trying with this: 

```
vl.markLine()
    .encode(
    vl.x().fieldT("Fecha"),
    vl.y().fieldQ(vl.repeat("layer")),
    vl.color().datum(vl.repeat("layer")),
  )  
  .repeat({layer: ["Muertes No hacer nada", "Muertes Cuarentena"]})
  .facet(vl.fieldN("ciudad"))
  .data(data)
  .render()
```

And I get this error: 

`TypeError: vl.markLine(...).encode(...).repeat(...).facet is not a function`

I have also tried switching the facet/repeat order but still can't get vega-lite-api to generate a spec that uses the facet operator.

More details with examples of the problem here: 

https://observablehq.com/d/a4d527cf6b567011

**Comment by jheer** [comment] 2020-04-28 15:15
Thanks for the issue! That indeed looks like a limitation in the API. I believe the code to fix is here: https://github.com/vega/vega-lite-api/blob/master/api/types.js#L482

It looks like we consistently augment specs with a repeat operator but not facet. I can't remember if this was due to a prior limitation in Vega-Lite or just an oversight in the code here. Either way, I will try to address this soon, when I make the next release for the latest VL version.

Can you confirm that the Vega-Lite JSON works as intended, and the issue is just an API shortcoming at this point?

**Comment by jheer** [comment] 2020-04-28 15:45
Ah yes, I left it out earlier because it creates a cyclic dependency in the generated API code. However, I added new tests and it appears the cycle is "safe" for now.

**Comment by jheer** [comment] 2020-04-28 15:46
Fixed in fc31de5bf342db858bcb68f795d71c7e95389361, included in new v0.11.0 release.

**Closed by jheer** 2020-04-28 15:46 UTC

**Comment by john-guerra** [comment] 2020-04-28 16:15
Awesomeeeee, tested, works!!!! 

Thanks a lot for all the great work!!!

 I'm going to try to learn from the bugfix to try to be more helpful in the future, not just submitting the bug but also providing a PR

**Comment by john-guerra** [comment] 2020-05-01 15:34
Hi, 

this one works:

```
vl
  .encode(...)
  .repeat(...)
  .facet(...)
  .data(...)
```

but this one doesn't


```
vl
  .data(...)
  .encode(...)
  .repeat(...)
  .facet(...)
```

See https://observablehq.com/d/a4d527cf6b567011#doesntWork, is this a bug?

**Comment by john-guerra** [comment] 2020-05-01 15:55
Also, how do you change the header and sorting of the facet operator. In vega-lite you can do
~~~ 
{
  ...,
  "facet": {
    ...,
    "sort": {},
    "header": {}
  },
  "spec": {...}
}
~~~

So I guess it should be like: 
~~~
vl.markLine()
  .encode(...)
  .facet(vl.field(...)
    .sort(...)
    .header(...)
  )
~~~

But I cannot get it to work either: https://observablehq.com/d/a4d527cf6b567011#facetParams

**Comment by jheer** [comment] 2020-05-01 16:15
In the first case involving the data method: No that is not a bug, though it is a bit unclear. The top-level data method binds the data to the next subsequent mark/chart definition, whatever that may be. We might be able to develop some additional routes in the future, but for now always bind the data *after* the desired repeat or facet call.

In the second case I believe you can use the top level facet directive, just like you would in an encoding channel: vl.facet().fieldN().header() etc.

**Comment by john-guerra** [comment] 2020-05-01 20:19
Thanks Jeef.

About the .data method. Ok, makes sense, maybe we can make it very clear in the documentation and tutorials. I'll take a look and make suggestions there.

For the facet with parameters, what if you have a repeat + facet combination, is there any way of setting the facet parameters there?

Updated the example here to reflect that https://observablehq.com/d/a4d527cf6b567011#chart

**Comment by jheer** [comment] 2020-05-01 21:40
I'm not sure I understand your last question. Let me better explain what I was suggesting. It looks like your example works if I pass the following input into the facet operator:

```js
.facet(
  vl.facet().field("Ciudad")
    .sort(vl.average("Muertes No hacer nada").order("descending"))    
    .header({labelFontSize: 16, labelAnchor:"end", labelOffset:80})
    .title(null)
)
```

Again, just like a facet encoding channel, but here passed as input to the facet operator!

**Comment by john-guerra** [comment] 2020-05-02 17:01
Got it! I wouldn't have figure it out on my own. Thanks!

Here is how it looks: 

vl
      .markLine({tooltip:true})
      .encode(
        vl.x().fieldT("Fecha")
          .axis({tickCount: 2}),
        vl.y().fieldQ(vl.repeat("layer"))
          .scale({domain: [0, 2000]})
          .title(null)
          .axis({tickCount: 2}),
        vl.color().datum(vl.repeat("layer"))
      )
      .width(100)
      .height(100)
      .repeat({layer: ["Muertes No hacer nada", "Muertes Cuarentena"]})
      .facet(vl.facet().field("Ciudad")
             .sort(vl.average("Muertes No hacer nada").order("descending"))    
             .header({labelFontSize: 16, labelAnchor:"end", labelOffset:80})
             .title(null)
      )
      .columns(2)
      .data(data)
      .render()

https://observablehq.com/d/a4d527cf6b567011#chart
